# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: SelecEval Documentation
site_url: https://jsincn.github.io/SelecEval/
theme:
  name: material

repo_url: https://github.com/jsincn/SelecEval

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences